server:
  port: ${SERVER_PORT:8083}
  servlet:
    session:
      cookie:
        name: AUTH_SESSION
        path: /
        http-only: true
        same-site: lax
spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:auth_user}
    password: ${SPRING_DATASOURCE_PASSWORD:auth_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
security:
  jwt:
    public-key-file: file:../dev-keys/public.pem
    private-key-file: file:../dev-keys/private.pem
    issuer: http://auth-service:8083
  cookie:
    secure: ${COOKIE_SECURE:false}
