spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
security:
  jwt:
    private-key-file: "file:../dev-keys/private.pem"
    public-key-file: "file:../dev-keys/public.pem"
    issuer: http://auth-service:8083