spring:
  application:
    name: auth-service
security:
  jwt:
    private-key-file: "file:../dev-keys/private.pem"
    public-key-file: "file:../dev-keys/public.pem"
    issuer: http://auth-service:8083