events {
}

http {
    resolver 127.0.0.11 valid=5s ipv6=off;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    upstream chat_client_instances {
        zone chat_client_instances 64k;
        server chat-client:8082 resolve;
    }

    server {
        listen 8082;

        location / {
            proxy_pass http://chat_client_instances;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 3600s;
        }
    }
}