services:
  auth-database:
    image: postgres:17
    container_name: auth-database

    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}

    volumes:
      - auth-database-data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: local_admin_password
    ports:
      - "5050:80"
    depends_on:
      auth-database:
        condition: service_healthy
  auth-service:
    build:
      context: ..
      dockerfile: auth-service/Dockerfile

    image: chat-platform/auth-service:local
    container_name: auth-service

    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      SECURITY_JWT_PUBLIC_KEY_FILE: file:/dev-keys/public.pem
      SECURITY_JWT_PRIVATE_KEY_FILE: file:/dev-keys/private.pem
      SECURITY_JWT_ISSUER: http://auth-service:8083

    volumes:
      - ../dev-keys:/dev-keys:ro

    ports:
      - "8083:8083"

    depends_on:
      auth-database:
        condition: service_healthy

volumes:
  auth-database-data: