chat:
  server:
    host: ${CHAT_SERVER_HOST:localhost}
    port: ${CHAT_SERVER_PORT:8080}

server:
  port: ${SERVER_PORT:8082}

# chat-client
security:
  jwt:
    public-key-file: "file:../dev-keys/public.pem"
    audience: chat-client
    issuer: http://auth-service:8083